version: '3'

services:
    db:
        image: my-mysql
        restart: always
        container_name: my-mysql
        #compose file has precedence over dockerfile, but its more clear to keep this in the dockerfile
        #environment:
            #MYSQL_DATABASE: 'spring_security_db'
            #MYSQL_USER: 'root'
            #MYSQL_PASSWORD: 'root'
            #MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3306:3306'
        #expose:
        #    - '3306'
        volumes:
            - my-db:/var/lib/mysql
    backend:
        image: java-spring-boot-app
        restart: always
        depends_on: 
            - db
        environment: 
            - WAIT_HOSTS=mysql:3306
        ports:
            - '8080:8080'
        expose:
            - '8080'

volumes:
    my-db:
